[platformio]
default_envs = esp32dev

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio

[env:esp32dev]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
board_build.flash_mode = ${common.board_build.flash_mode}

[env:polling]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
board_build.flash_mode = ${common.board_build.flash_mode}
build_flags =
    -D EXAMPLE=1

[env:interrupt]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
board_build.flash_mode = ${common.board_build.flash_mode}
build_flags =
    -D EXAMPLE=2

[env:interrupt_queue]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
board_build.flash_mode = ${common.board_build.flash_mode}
build_flags =
    -D EXAMPLE=3
